Added two other blockchain technology related podcasts
thisdot/tech-podcasts pull request #54
Opened 2023-01-01 00:37 UTC by c0d33ngr

## New Podcast Suggestion

- [ ] Podcast Suggestion is not a duplicate
- [ ] Title of the podcast is added to the proper category
- [ ] Link to the podcast is added beside the title
- [ ] Title and Link are accurate

2023-01-02 22:22 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-01-02 22:22 UTC, jdwilkin4 commented on README.md
> +- [CoinDesk Podcast Network](https://www.coindesk.com/podcasts/coindesk-podcast-network/)
This needs to go before Cryptoknights because the entire list is in alphabetical order

2023-01-02 22:22 UTC, jdwilkin4 commented on README.md
> +- [The Blockchain.com Podcast](https://www.blockchain.com/podcast)
This needs to be go before The third Web podcast because the entire list is in alphabetical order

2023-01-03 03:51 UTC, c0d33ngr commented
Thank you. I didn't notice they were suppose to be in alphabetical order

2023-01-03 09:58 UTC, c0d33ngr commented
I've sorted them in alphabetical order @jdwilkin4

2023-01-03 15:43 UTC, merged